### ISSUE TITLE
test to see if the code runs before bumping the deps in order to prevent deprecation 

### ISSUE THREAD

**Issue by load1n9** [azurystudio/bump#12]

**Comment by boywithkeyboard** [comment]
@load1n9 ok, so the reusable workflow would look something like

```yml
name: 'bump'

on:
  workflow_call:
    inputs:
      assignees:
        default: ''
        required: false
        type: 'string'
      reviewers:
        required: true
        type: 'string'
      test:
        default: 'WHAT COMMAND AS FALLBACK?'
        required: false
        type: 'string'
    secrets:
      token:
        required: true

jobs:
  bump:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: 'actions/checkout@v3'

      - uses: 'denoland/setup-deno@v1'
        with:
          deno-version: 'v1.x'

      - name: 'bump dependencies'
        run: |
          deno run -A https://raw.githubusercontent.com/azurystudio/bump/v0/mod.ts
          CHANGELOG=$(cat dependencies_changelog.md)
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          rm dependencies_changelog.md

      - name: 'create pull request'
        uses: 'peter-evans/create-pull-request@v4'
        with:
          reviewers: '${{ inputs.reviewers }}'
          token: '${{ secrets.token }}'
          title: 'bump dependencies'
          author: 'GitHub <noreply@github.com>'
          commit-message: 'bump dependencies'
          body: '${{ env.CHANGELOG }}'
          labels: 'dependencies'
          delete-branch: true
          branch: 'bump'

      - id: 'commit'
        run: |
          echo "::set-output name=sha::$(git rev-parse HEAD)"
      
      - uses: 'Sibz/github-status-action@v1'
        with:
          authToken: '${{ secrets.token }}'
          context: 'test updates'
          state: 'pending'
          sha: '${{ steps.commit.outputs.sha }}'

      - name: 'test updates'
        id: 'test'
        continue-on-error: true
        run: '${{ inputs.test }}'

      - name: 'set commit status with outcome'
        uses: 'Sibz/github-status-action@v1'
        with:
          authToken: '${{ secrets.token }}'
          context: 'test updates'
          state: '${{ steps.test.outcome }}'
          sha: '${{ steps.commit.outputs.sha }}'
```

but i have no idea how to make testing completely optional, or a fallback command if no test command is specified?
